const KEY="khedmet_elamir_db_v2";
const seed={
 settings:{notifications:true,dark:false,birthday:true,autoSave:true,brightness:100},
 classes:["أولى إعدادي","ثانية إعدادي","ثالثة إعدادي","أولى ثانوي","ثانية ثانوي","ثالثة ثانوي","خريجين"],
 members:[
 {id:"1001",name:"مريم إبراهيم",gender:"أنثى",birth:"2009-09-12",phone:"0123456789",address:"القاهرة",className:"ثانوي",status:"منتظم",notes:"",created:"2026-01-10"},
 {id:"1002",name:"كيرلس بطرس",gender:"ذكر",birth:"2010-09-15",phone:"0112345678",address:"الجيزة",className:"إعدادي",status:"منتظم",notes:"",created:"2026-01-11"},
 {id:"1003",name:"فادي عادل",gender:"ذكر",birth:"2008-12-02",phone:"0109876543",address:"القاهرة",className:"ثانوي",status:"متابعة",notes:"",created:"2026-02-03"},
 {id:"1004",name:"جورج مينا",gender:"ذكر",birth:"2011-09-21",phone:"0129876543",address:"الجيزة",className:"إعدادي",status:"منتظم",notes:"",created:"2026-02-08"},
 {id:"1005",name:"مارينا سامح",gender:"أنثى",birth:"2012-10-03",phone:"0156789123",address:"القاهرة",className:"إعدادي",status:"غياب",notes:"",created:"2026-03-01"},
 {id:"1006",name:"بيتر وديع",gender:"ذكر",birth:"2007-06-19",phone:"0101234567",address:"الجيزة",className:"خريجين",status:"منتظم",notes:"",created:"2026-03-04"}
 ],
 attendance:[], visits:[]
};
let db=load(), current="dashboard", selectedProfile="";
const API_BASE = (location.protocol === "http:" || location.protocol === "https:") ? "" : null;
let serverSyncBusy = false;
function load(){try{return JSON.parse(localStorage.getItem(KEY))||structuredClone(seed)}catch{return structuredClone(seed)}}
function save(){localStorage.setItem(KEY,JSON.stringify(db)); if(API_BASE) syncToServer()}
async function syncToServer(){if(serverSyncBusy)return;serverSyncBusy=true;try{await fetch("/api/db",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(db)})}catch(e){console.warn("تعذر مزامنة البيانات مع الخادم",e)}finally{serverSyncBusy=false}}
async function loadFromServer(){if(!API_BASE)return;try{let r=await fetch("/api/db");if(!r.ok)return;let remote=await r.json();if(remote&&Array.isArray(remote.members)&&Array.isArray(remote.classes)){db=remote;localStorage.setItem(KEY,JSON.stringify(db));if(document.getElementById("main")&&current!=="login")go(current)}}catch(e){console.warn("تعذر تحميل البيانات من الخادم",e)}}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function toast(t){let x=document.getElementById("toast");x.textContent=t;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),1800)}
function app(){document.getElementById("app").innerHTML=`<header class="top"><div class="brand"><div class="brand-logo">✚</div>خدمة الأمير</div><div class="user"><span>الخادم</span><div class="avatar">ب</div></div></header><aside class="side"><div class="brand"><div class="brand-logo">✚</div>خدمة الأمير</div><nav class="nav">${nav()}</nav><button class="logout" onclick="logout()">↪ تسجيل الخروج</button></aside><main id="main"></main><nav class="mobile">${mobileNav()}</nav>`;go(current)}
function nav(){return [["dashboard","⌂","الرئيسية"],["members","👥","المخدومين"],["classes","▣","الفصول"],["attendance","✓","الحضور"],["visits","♡","الافتقاد"],["birthdays","🎂","أعياد الميلاد"],["stats","▥","الإحصائيات"],["data","⇄","البيانات"],["settings","⚙","الإعدادات"]].map(x=>`<button class="${current===x[0]?"active":""}" onclick="go('${x[0]}')">${x[1]} &nbsp; ${x[2]}</button>`).join("")}
function mobileNav(){return [["dashboard","⌂","الرئيسية"],["members","👥","المخدومين"],["attendance","✓","الحضور"],["visits","♡","الافتقاد"],["settings","☰","المزيد"]].map(x=>`<button onclick="go('${x[0]}')">${x[1]}<small>${x[2]}</small></button>`).join("")}
function go(p){current=p;document.getElementById("main").innerHTML=pages[p]();document.querySelector(".nav").innerHTML=nav();bind()}
function title(t,s,b=""){return `<div class="title"><div><h1>${t}</h1><div class="sub">${s}</div></div>${b}</div>`}
function stat(i,t,n,c=""){return `<div class="stat"><div><div class="sub">${t}</div><div class="n">${n}</div></div><div class="ico ${c}">${i}</div></div>`}
function pages(){return {dashboard,members,classes,attendance,visits,birthdays,stats,dataPage,settings,about:aboutPage,profile:()=>profilePage(selectedProfile)}[current]||dashboard}
function dashboard(){let present=db.attendance.filter(x=>x.date===today()&&x.state==="present").length;let absent=db.attendance.filter(x=>x.date===today()&&x.state==="absent").length;return title("مرحبًا 👋","ملخص خدمة الأمير اليوم",`<button class="btn primary" onclick="memberForm()">＋ إضافة مخدوم</button>`)+`<div class="grid stats">${stat("👥","المخدومين",db.members.length)}${stat("✓","الحضور اليوم",present,"green")}${stat("×","الغياب اليوم",absent,"red")}${stat("🎂","أعياد قريبة",birthdayList().length,"gold")}</div><div class="grid two"><div class="card"><h3>خدمات سريعة</h3><div class="quick">${[["👥","المخدومين","members"],["▣","الفصول","classes"],["✓","الحضور","attendance"],["♡","الافتقاد","visits"],["🎂","أعياد الميلاد","birthdays"],["▥","الإحصائيات","stats"],["⇄","البيانات","data"],["⚙","الإعدادات","settings"]].map(q=>`<button onclick="go('${q[2]}')"><b>${q[0]}</b>${q[1]}</button>`).join("")}</div></div><div class="card"><h3>نسبة الحضور اليوم</h3><div style="font-size:38px;font-weight:bold;margin:25px 0">${attendanceRate()}%</div><div class="barbg"><i style="width:${attendanceRate()}%"></i></div><div class="sub">يمكنك تسجيل الحضور من قسم الحضور أو باستخدام QR.</div></div></div>`}
function attendanceRate(){let a=db.attendance.filter(x=>x.date===today());if(!a.length)return 0;return Math.round(a.filter(x=>x.state==="present").length/a.length*100)}
function members(){return title("المخدومين","إضافة وتعديل وحذف والبحث في جميع البيانات",`<button class="btn primary" onclick="memberForm()">＋ إضافة مخدوم</button>`)+`<div class="card"><div class="toolbar"><input id="search" class="search" placeholder="ابحث بالاسم أو الهاتف أو ID"><button class="btn" onclick="memberForm()">＋ جديد</button></div><div class="table-wrap"><table class="table"><thead><tr><th>المخدوم</th><th>ID</th><th>الفصل</th><th>تاريخ الميلاد</th><th>الهاتف</th><th>الحالة</th><th>إجراءات</th></tr></thead><tbody id="rows">${memberRows(db.members)}</tbody></table></div></div>`}
function memberRows(a){return a.map(m=>`<tr><td><div class="person"><div class="avatar">${esc(m.name[0])}</div><b>${esc(m.name)}</b></div></td><td>${m.id}</td><td>${esc(m.className)}</td><td>${esc(m.birth)}</td><td>${esc(m.phone)}</td><td><span class="pill ${m.status==="منتظم"?"ok":m.status==="متابعة"?"warn":"bad"}">${esc(m.status)}</span></td><td><button class="btn" onclick="openProfile('${m.id}')">عرض</button> <button class="btn" onclick="memberForm('${m.id}')">تعديل</button> <button class="btn danger" onclick="removeMember('${m.id}')">حذف</button></td></tr>`).join("")}
function bind(){let s=document.getElementById("search");if(s)s.oninput=()=>document.getElementById("rows").innerHTML=memberRows(db.members.filter(m=>(m.name+" "+m.phone+" "+m.id).includes(s.value)));}
function classes(){return title("الفصول","إنشاء الفصول ومتابعة عدد المخدومين",`<button class="btn primary" onclick="classForm()">＋ فصل جديد</button>`)+`<div class="grid cards">${db.classes.map((c,i)=>{let n=db.members.filter(m=>m.className===c).length;return `<div class="class-card"><h3>${esc(c)}</h3><div class="sub">${n} مخدوم</div><div class="barbg"><i style="width:${Math.min(100,n*8+20)}%"></i></div><div class="actions" style="margin-top:16px"><button class="btn" onclick="classMembers('${esc(c)}')">عرض</button><button class="btn danger" onclick="removeClass('${esc(c)}')">حذف</button></div></div>`}).join("")}</div>`}
function attendance(){let d=today();return title("الحضور","أنشئ يوم حضور ثم سجل حاضر/غائب/متأخر",`<button class="btn primary" onclick="newAttendanceDay()">＋ يوم حضور</button>`)+`<div class="card"><div class="toolbar"><input id="attDate" type="date" class="field" value="${d}"><select id="attClass" class="field"><option value="">كل الفصول</option>${db.classes.map(c=>`<option>${esc(c)}</option>`).join("")}</select><button class="btn" onclick="renderAttendance()">تحديث</button><button class="btn" onclick="scanQR('attendance')">▣ مسح QR</button></div><div class="table-wrap"><table class="table"><thead><tr><th>المخدوم</th><th>الفصل</th><th>حاضر</th><th>متأخر</th><th>غائب</th></tr></thead><tbody id="attRows">${attendanceRows(d,"")}</tbody></table></div></div>`}
function attendanceRows(d,c){return db.members.filter(m=>!c||m.className===c).map(m=>{let rec=db.attendance.find(x=>x.id===m.id&&x.date===d);return `<tr><td>${esc(m.name)}</td><td>${esc(m.className)}</td><td><button class="pill ok" onclick="setAtt('${m.id}','${d}','present')">✓ ${rec?.state==="present"?"محدد":""}</button></td><td><button class="pill warn" onclick="setAtt('${m.id}','${d}','late')">◷ ${rec?.state==="late"?"محدد":""}</button></td><td><button class="pill bad" onclick="setAtt('${m.id}','${d}','absent')">× ${rec?.state==="absent"?"محدد":""}</button></td></tr>`}).join("")}
function renderAttendance(){let d=document.getElementById("attDate").value,c=document.getElementById("attClass").value;document.getElementById("attRows").innerHTML=attendanceRows(d,c)}
function setAtt(id,date,state){db.attendance=db.attendance.filter(x=>!(x.id===id&&x.date===date));db.attendance.push({id,date,state});save();renderAttendance();toast("تم حفظ الحالة")}
function visits(){return title("الافتقاد","متابعة الافتقاد وتسجيل أيام المتابعة",`<button class="btn primary" onclick="newVisitDay()">＋ يوم افتقاد</button>`)+`<div class="card"><div class="toolbar"><input id="visitDate" type="date" class="field" value="${today()}"><button class="btn" onclick="renderVisits()">تحديث</button><button class="btn" onclick="scanQR('visit')">▣ مسح QR</button></div><div class="table-wrap"><table class="table"><thead><tr><th>المخدوم</th><th>الفصل</th><th>تم الافتقاد</th><th>لم يتم</th></tr></thead><tbody id="visitRows">${visitRows(today())}</tbody></table></div></div>`}
function visitRows(d){return db.members.map(m=>{let r=db.visits.find(x=>x.id===m.id&&x.date===d);return `<tr><td>${esc(m.name)}</td><td>${esc(m.className)}</td><td><button class="pill ok" onclick="setVisit('${m.id}','${d}',true)">✓ ${r?.done?"محدد":""}</button></td><td><button class="pill bad" onclick="setVisit('${m.id}','${d}',false)">× ${r?.done===false?"محدد":""}</button></td></tr>`}).join("")}
function renderVisits(){let d=document.getElementById("visitDate").value;document.getElementById("visitRows").innerHTML=visitRows(d)}
function setVisit(id,date,done){db.visits=db.visits.filter(x=>!(x.id===id&&x.date===date));db.visits.push({id,date,done});save();renderVisits();toast("تم حفظ الافتقاد")}
function birthdays(){let a=birthdayList();return title("أعياد الميلاد","المواعيد القادمة حسب تاريخ الميلاد",`<button class="btn" onclick="toast('سيظهر تذكير يومي عند تفعيل الإعداد')">🔔 التذكير</button>`)+`<div class="grid cards">${a.map(m=>`<div class="card"><div style="display:flex;gap:12px;align-items:center"><div class="photo" style="width:60px;height:60px;font-size:25px;margin:0">🎂</div><div><b>${esc(m.name)}</b><div class="sub">${esc(m.birth)} • ${esc(m.className)}</div></div></div></div>`).join("")||`<div class="card">لا توجد أعياد ميلاد قريبة.</div>`}</div>`}
function birthdayList(){let now=new Date();let mm=now.getMonth()+1,dd=now.getDate();return db.members.filter(m=>{if(!/^\d{4}-\d{2}-\d{2}$/.test(m.birth))return false;let p=m.birth.split("-");let d=Math.abs((+p[1]-mm)*31+(+p[2]-dd));return d<=31||d>=330}).sort((a,b)=>a.birth.slice(5).localeCompare(b.birth.slice(5)))}
function stats(){let present=db.attendance.filter(x=>x.state==="present").length,absent=db.attendance.filter(x=>x.state==="absent").length,vis=db.visits.filter(x=>x.done).length;return title("الإحصائيات","الحضور والغياب والافتقاد مع رسوم بيانية")+`<div class="grid stats">${stat("✓","إجمالي الحضور",present,"green")}${stat("×","إجمالي الغياب",absent,"red")}${stat("♡","إجمالي الافتقاد",vis,"gold")}${stat("👥","المخدومين",db.members.length)}</div><div class="card" style="margin-top:18px"><h3>الحضور حسب الأيام المسجلة</h3><div class="chart">${Object.entries(groupDays()).slice(-8).map(([d,v])=>`<div class="bar" style="height:${Math.max(8,v?Math.min(100,v):8)}%"><span>${d.slice(5)}</span></div>`).join("")}</div></div>`}
function groupDays(){let o={};db.attendance.forEach(x=>{o[x.date]=(o[x.date]||0)+(x.state==="present"?10:0)});return o}
function dataPage(){return title("البيانات","نسخ احتياطي واسترجاع واستيراد وتصدير Excel")+`<div class="grid two"><div class="card"><h3>نسخة احتياطية كاملة</h3><p class="sub">يحفظ جميع الفصول والمخدومين والحضور والافتقاد.</p><div class="actions"><button class="btn primary" onclick="backup()">⇩ تنزيل نسخة</button><label class="btn">⇧ استرجاع نسخة<input id="restore" type="file" accept=".json" hidden></label></div></div><div class="card"><h3>Excel</h3><p class="sub">استيراد قائمة المخدومين أو استخراجها.</p><div class="actions"><button class="btn primary" onclick="exportExcel()">⇩ تصدير Excel</button><label class="btn">⇧ استيراد Excel<input id="excel" type="file" accept=".xlsx,.xls,.csv" hidden></label></div></div></div><div class="card" style="margin-top:18px"><h3>قاعدة البيانات</h3><p class="sub">البيانات محفوظة محليًا في المتصفح. يمكن لاحقًا ربطها بقاعدة بيانات أونلاين لمشاركة نفس البيانات بين عدة أجهزة وخدام.</p><button class="btn danger" onclick="resetDB()">مسح البيانات التجريبية وإعادة البداية</button></div>`}
function settings(){return title("الإعدادات","تحكم في إعدادات الموقع وتفضيلاتك")+`<div class="settings-list card">${setting("الإشعارات","notifications")}${brightnessControl()}${setting("الوضع الليلي","dark")}${settingLink("🛡️","الخصوصية","toast('إعدادات الخصوصية محفوظة محليًا في هذه النسخة')")}${settingLink("ℹ️","عن الموقع","go('about')")}${settingLink("❓","المساعدة","toast('للمساعدة: استخدم القوائم أو تواصل مع مسؤول الخدمة')")}<div class="setting logout-setting" onclick="logout()"><span>🚪 تسجيل الخروج</span><b>خروج</b></div></div>`}
function settingLink(icon,label,action){return `<div class="setting-link" onclick="${action}"><span><b class="setting-icon">${icon}</b>${label}</span><b>‹</b></div>`}
function brightnessControl(){let value=Number(db.settings.brightness||100);return `<div class="setting brightness-row"><span>إضاءة الشاشة</span><div class="brightness"><input type="range" min="60" max="120" value="${value}" oninput="setBrightness(this.value)"><b>${value}%</b></div></div>`}
function setBrightness(value){db.settings.brightness=Number(value);document.body.style.filter=`brightness(${Number(value)/100})`;save();let b=document.querySelector('.brightness b');if(b)b.textContent=value+'%'}
function toggleSetting(k){db.settings[k]=!db.settings[k];if(k==='dark')document.body.classList.toggle('dark-mode',db.settings[k]);save();go('settings')}
function openProfile(id){selectedProfile=id;go('profile')}
function aboutPage(){return title("عن الموقع","معلومات موقع خدمة الأمير",`<button class="btn" onclick="go('settings')">← العودة</button>`)+`<div class="about card"><div class="about-logo">✚</div><h2>خدمة الأمير</h2><p class="sub">موقع مخصص لخدمة الأمير</p><div class="about-text"><h3>نبذة عن الموقع</h3><p>موقع خدمة الأمير هو منصة إلكترونية تم إنشاؤها لأجل الخدمة، بهدف تسهيل التواصل والمتابعة وتنظيم الأنشطة والخدمات المختلفة للكنيسة.</p></div><div class="info">${info("إصدار الموقع","v1.0")}${info("التطوير","PK")}${info("حقوق الملكية","جميع الحقوق محفوظة © خدمة الأمير 2025")}</div></div>`}
function profilePage(id){let m=db.members.find(x=>x.id===id);if(!m)return members();return title("بيانات المخدوم","كل التفاصيل والإجراءات",`<button class="btn" onclick="go('members')">← العودة</button>`)+`<div class="grid profile"><div class="card" style="text-align:center"><div class="photo">${esc(m.name[0])}</div><h2>${esc(m.name)}</h2><div class="sub">${esc(m.className)} • ID ${m.id}</div><div class="actions" style="justify-content:center;margin-top:16px"><button class="btn primary" onclick="memberForm('${m.id}')">تعديل</button><button class="btn" onclick="showQR('${m.id}')">▣ QR</button><a class="btn" href="tel:${esc(m.phone)}">☎ اتصال</a></div></div><div class="card"><h3>البيانات الأساسية</h3><div class="info">${info("الاسم",m.name)}${info("النوع",m.gender)}${info("تاريخ الميلاد",m.birth)}${info("الهاتف",m.phone)}${info("العنوان",m.address)}${info("الفصل",m.className)}${info("الحالة",m.status)}${info("ملاحظات",m.notes||"—")}</div><h3 style="margin-top:24px">سجل مختصر</h3><p class="sub">حضور: ${db.attendance.filter(x=>x.id===m.id&&x.state==="present").length} • غياب: ${db.attendance.filter(x=>x.id===m.id&&x.state==="absent").length} • افتقاد: ${db.visits.filter(x=>x.id===m.id&&x.done).length}</p></div></div>`}
function info(a,b){return `<div><small>${esc(a)}</small>${esc(b)}</div>`}
function memberForm(id=""){let m=db.members.find(x=>x.id===id)||{id:String(Date.now()).slice(-6),name:"",gender:"ذكر",birth:"",phone:"",address:"",className:db.classes[0]||"",status:"منتظم",notes:""};modal(`<div class="modal-head"><h2>${id?"تعديل المخدوم":"إضافة مخدوم"}</h2><button class="btn" onclick="closeModal()">✕</button></div><div class="form-grid">${field("الاسم","name",m.name)}${field("ID","id",m.id)}${field("النوع","gender",m.gender,"select",["ذكر","أنثى"])}${field("تاريخ الميلاد","birth",m.birth,"date")}${field("الهاتف","phone",m.phone)}${field("الفصل","className",m.className,"select",db.classes)}${field("العنوان","address",m.address,"full")}${field("الحالة","status",m.status,"select",["منتظم","متابعة","غياب"])}${field("ملاحظات","notes",m.notes,"textarea","",true)}</div><div class="actions" style="margin-top:18px;justify-content:flex-start"><button class="btn primary" onclick="saveMember('${id}')">حفظ</button><button class="btn" onclick="closeModal()">إلغاء</button></div>`)}
function field(label,k,v,type="text",opts=[],full=false){let h=type==="select"?`<select id="f_${k}">${opts.map(o=>`<option ${o===v?"selected":""}>${esc(o)}</option>`).join("")}</select>`:type==="textarea"?`<textarea id="f_${k}" rows="3">${esc(v)}</textarea>`:`<input id="f_${k}" type="${type}" value="${esc(v)}">`;return `<label class="${full?"full":""}">${label}${h}</label>`}
function saveMember(old){let m={id:v("id").trim(),name:v("name").trim(),gender:v("gender"),birth:v("birth"),phone:v("phone").trim(),address:v("address").trim(),className:v("className"),status:v("status"),notes:v("notes").trim(),created:db.members.find(x=>x.id===old)?.created||today()};if(!m.id||!m.name)return toast("من فضلك أدخل الاسم وID");if(db.members.some(x=>x.id===m.id&&x.id!==old))return toast("هذا الـID مستخدم بالفعل");let i=db.members.findIndex(x=>x.id===old);if(i>=0)db.members[i]=m;else db.members.push(m);save();closeModal();go("members");toast("تم حفظ بيانات المخدوم") }
function v(k){return document.getElementById("f_"+k)?.value||""}
function removeMember(id){if(!confirm("هل تريد حذف هذا المخدوم؟"))return;db.members=db.members.filter(x=>x.id!==id);db.attendance=db.attendance.filter(x=>x.id!==id);db.visits=db.visits.filter(x=>x.id!==id);save();go("members");toast("تم الحذف")}
function classForm(){modal(`<div class="modal-head"><h2>إضافة فصل</h2><button class="btn" onclick="closeModal()">✕</button></div><input id="className" class="search" placeholder="اسم الفصل"><button class="btn primary wide" onclick="addClass()">حفظ</button>`)}
function addClass(){let x=document.getElementById("className").value.trim();if(!x)return toast("اكتب اسم الفصل");if(db.classes.includes(x))return toast("الفصل موجود بالفعل");db.classes.push(x);save();closeModal();go("classes");toast("تم إنشاء الفصل")}
function removeClass(c){if(db.members.some(m=>m.className===c))return toast("لا يمكن حذف فصل به مخدومين");db.classes=db.classes.filter(x=>x!==c);save();go("classes")}
function classMembers(c){go("members");setTimeout(()=>{let s=document.getElementById("search");s.value=c;s.dispatchEvent(new Event("input"))},0)}
function validDate(d){return /^\d{4}-\d{2}-\d{2}$/.test(d)&&!Number.isNaN(Date.parse(d))}
function newAttendanceDay(){let d=prompt("اكتب تاريخ يوم الحضور YYYY-MM-DD",today());if(!d)return;if(!validDate(d))return toast("التاريخ غير صحيح");document.getElementById("attDate")&&(document.getElementById("attDate").value=d);toast("تم تحديد يوم الحضور")}
function newVisitDay(){let d=prompt("اكتب تاريخ يوم الافتقاد YYYY-MM-DD",today());if(!d)return;if(!validDate(d))return toast("التاريخ غير صحيح");document.getElementById("visitDate")&&(document.getElementById("visitDate").value=d);toast("تم تحديد يوم الافتقاد")}
function showQR(id){modal(`<div class="modal-head"><h2>QR للمخدوم</h2><button class="btn" onclick="closeModal()">✕</button></div><div class="qr"><div id="qr"></div><p class="sub">ID: ${esc(id)}</p></div>`);new QRCode(document.getElementById("qr"),{text:id,width:210,height:210})}
function scanQR(kind){modal(`<div class="modal-head"><h2>مسح QR</h2><button class="btn" onclick="closeModal()">✕</button></div><div style="padding:20px;text-align:center"><p>هذه النسخة تعرض نظام QR وتجهيز الـID. للمسح بالكاميرا يحتاج الموقع المنشور إلى صلاحية كاميرا وطبقة QR scanner.</p><input id="qrid" class="search" placeholder="أدخل ID للتجربة"><button class="btn primary wide" onclick="applyQR('${kind}')">تسجيل</button></div>`)}
function applyQR(kind){let id=document.getElementById("qrid").value.trim();if(!db.members.some(x=>x.id===id))return toast("ID غير موجود");closeModal();if(kind==="attendance"){setAtt(id,today(),"present")}else setVisit(id,today(),true)}
function backup(){let blob=new Blob([JSON.stringify(db,null,2)],{type:"application/json"});download(blob,"khedmet-elamir-backup.json")}
function download(blob,name){let a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();URL.revokeObjectURL(a.href)}
function exportExcel(){let rows=db.members.map(m=>({ID:m.id,الاسم:m.name,النوع:m.gender,تاريخ_الميلاد:m.birth,الهاتف:m.phone,العنوان:m.address,الفصل:m.className,الحالة:m.status,ملاحظات:m.notes}));let ws=XLSX.utils.json_to_sheet(rows),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,"المخدومين");XLSX.writeFile(wb,"خدمة_الأمير_المخدومين.xlsx")}
function resetDB(){if(confirm("سيتم حذف البيانات المحلية وإرجاع البيانات التجريبية.")){db=structuredClone(seed);save();go("dashboard");toast("تمت إعادة البداية")}}
function modal(html){document.getElementById("modal").innerHTML=`<div class="modal-box">${html}</div>`;document.getElementById("modal").classList.remove("hidden")}
function closeModal(){document.getElementById("modal").classList.add("hidden")}
function showLogin(message=""){
  document.getElementById("app").innerHTML=`<section class="login"><div class="hero"><div class="hero-box"><div class="logo">✚</div><h1>خدمة الأمير</h1><p>إدارة المخدومين والحضور والافتقاد بطريقة بسيطة ومنظمة.</p></div></div><div class="login-card"><h2 id="authTitle">تسجيل الدخول</h2><label>رقم الهاتف</label><input id="phone" inputmode="tel" autocomplete="tel" placeholder="01xxxxxxxxx"><label>كلمة المرور</label><input id="password" type="password" autocomplete="current-password" placeholder="8 أحرف على الأقل"><label class="remember"><input id="remember" type="checkbox"> تذكرني</label><div id="authError" class="sub" style="color:#d33">${esc(message)}</div><button class="wide primary" onclick="submitAuth('login')">دخول</button><button class="link" onclick="toggleRegister()" id="toggleAuth">إنشاء حساب جديد</button></div></section>`;
}
function toggleRegister(){
  const title=document.getElementById("authTitle"); const btn=document.querySelector('.login-card button.primary'); const toggle=document.getElementById('toggleAuth');
  const registering=title.dataset.mode==='register'; title.dataset.mode=registering?'login':'register';
  title.textContent=registering?'تسجيل الدخول':'إنشاء حساب'; btn.textContent=registering?'دخول':'إنشاء الحساب'; btn.setAttribute('onclick',`submitAuth('${registering?'login':'register'}')`); toggle.textContent=registering?'إنشاء حساب جديد':'لديك حساب؟ تسجيل الدخول';
}
async function submitAuth(mode){
  const phone=document.getElementById('phone').value.trim(); const password=document.getElementById('password').value; const remember=document.getElementById('remember').checked;
  const error=document.getElementById('authError'); error.textContent='جارٍ التحقق...';
  try{const r=await fetch(`/api/auth/${mode}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({phone,password,remember})}); const data=await r.json(); if(!r.ok) throw new Error(data.error||'تعذر تنفيذ العملية'); app(); await loadFromServer(); toast(mode==='register'?'تم إنشاء الحساب وتسجيل الدخول':'مرحبًا بك في خدمة الأمير');}
  catch(e){error.textContent=e.message;}
}
async function logout(){try{await fetch('/api/auth/logout',{method:'POST'});}catch{} showLogin();}
function today(){let d=new Date();let m=String(d.getMonth()+1).padStart(2,"0");let day=String(d.getDate()).padStart(2,"0");return `${d.getFullYear()}-${m}-${day}`}
document.addEventListener("change",e=>{if(e.target.id==="restore"&&e.target.files[0]){let r=new FileReader();r.onload=()=>{try{db=JSON.parse(r.result);save();go("dashboard");toast("تم استرجاع النسخة")}catch{toast("الملف غير صالح")}};r.readAsText(e.target.files[0])}if(e.target.id==="excel"&&e.target.files[0]){let r=new FileReader();r.onload=()=>{let wb=XLSX.read(r.result,{type:"array"}),rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]]);rows.forEach(x=>{let m={id:String(x.ID||Date.now()+Math.random()).slice(0,10),name:x["الاسم"]||"",gender:x["النوع"]||"ذكر",birth:x["تاريخ_الميلاد"]||"",phone:String(x["الهاتف"]||""),address:x["العنوان"]||"",className:x["الفصل"]||db.classes[0]||"",status:x["الحالة"]||"منتظم",notes:x["ملاحظات"]||"",created:today()};if(m.name)db.members.push(m)});save();go("members");toast("تم استيراد ملف Excel")};r.readAsArrayBuffer(e.target.files[0])}});
if(db.settings?.dark)document.body.classList.add("dark-mode");
if(db.settings?.brightness)document.body.style.filter=`brightness(${Number(db.settings.brightness)/100})`;
(async()=>{try{const r=await fetch('/api/me');const data=await r.json();if(data.user){app();await loadFromServer();}else showLogin();}catch{showLogin();}})();
