const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const {init,getState,updateState,findUser,countUsers,createUser}=require('./db');
const ROOT=__dirname,PORT=Number(process.env.PORT||3000),MAX_BODY=5*1024*1024,SESSION_TTL=1000*60*60*24*30;
const attempts=new Map();const SECRET=process.env.SESSION_SECRET||crypto.randomBytes(48).toString('hex');
const seed={settings:{notifications:true,dark:false,birthday:true,autoSave:true,brightness:100},classes:['أولى إعدادي','ثانية إعدادي','ثالثة إعدادي','أولى ثانوي','ثانية ثانوي','ثالثة ثانوي','خريجين'],members:[],attendance:[],visits:[]};
function send(res,status,body,type='application/json; charset=utf-8'){const h={'Content-Type':type,'Cache-Control':type.startsWith('application/json')?'no-store':'public, max-age=3600','X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY','Referrer-Policy':'same-origin','Permissions-Policy':'camera=(self), microphone=()'};if(process.env.NODE_ENV==='production')h['Strict-Transport-Security']='max-age=31536000; includeSubDomains';res.writeHead(status,h);res.end(type.startsWith('application/json')?JSON.stringify(body):body)}
function bodyJson(req,limit=MAX_BODY){return new Promise((ok,no)=>{let raw='';req.on('data',c=>{raw+=c;if(raw.length>limit){no(Object.assign(new Error(),{status:413}));req.destroy()}});req.on('end',()=>{try{ok(JSON.parse(raw||'{}'))}catch{no(Object.assign(new Error(),{status:400}))}});req.on('error',no)})}
function phone(v){let p=String(v||'').replace(/\D/g,'');if(p.startsWith('20'))p=p.slice(2);if(p.startsWith('0'))p=p.slice(1);return p}function validPhone(p){return /^1[0125]\d{8}$/.test(p)}
function hash(p,s=crypto.randomBytes(16).toString('hex')){return new Promise((r,j)=>crypto.scrypt(p,s,64,(e,k)=>e?j(e):r(`${s}:${k.toString('hex')}`)))}async function verify(p,stored){const [s,h]=String(stored||'').split(':');if(!s||!h)return false;const x=(await hash(p,s)).split(':')[1];return crypto.timingSafeEqual(Buffer.from(x,'hex'),Buffer.from(h,'hex'))}
function cookies(req){return Object.fromEntries((req.headers.cookie||'').split(';').map(x=>x.trim()).filter(Boolean).map(x=>{const i=x.indexOf('=');return [x.slice(0,i),decodeURIComponent(x.slice(i+1))]}));}
function token(user,exp){const b=Buffer.from(JSON.stringify({user,exp})).toString('base64url');return `${b}.${crypto.createHmac('sha256',SECRET).update(b).digest('base64url')}`}
function current(req){try{const [b,s]=String(cookies(req).session||'').split('.');const e=crypto.createHmac('sha256',SECRET).update(b).digest('base64url');if(!b||!s||!crypto.timingSafeEqual(Buffer.from(s),Buffer.from(e)))return null;const p=JSON.parse(Buffer.from(b,'base64url'));return p.exp>Date.now()?p.user:null}catch{return null}}
function auth(req,res){const u=current(req);if(!u)send(res,401,{error:'يجب تسجيل الدخول أولاً'});return u}
function limited(req){const ip=req.socket.remoteAddress||'unknown',now=Date.now(),x=attempts.get(ip)||{n:0,t:now};if(now-x.t>900000){x.n=0;x.t=now}x.n++;attempts.set(ip,x);return x.n>20}
function safe(u){const target=u==='/'?'/index.html':decodeURIComponent(u.split('?')[0]),full=path.resolve(ROOT,'.'+target);return full.startsWith(path.resolve(ROOT))?full:null}
(async()=>{await init();http.createServer(async(req,res)=>{const route=req.url.split('?')[0];try{
if(req.method==='GET'&&route==='/api/health')return send(res,200,{ok:true,service:'khedmet-elamir',database:'postgresql'});
if(req.method==='GET'&&route==='/api/me')return send(res,200,{user:current(req)});
if(req.method==='POST'&&route==='/api/auth/logout'){res.setHeader('Set-Cookie','session=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0');return send(res,200,{ok:true})}
if(req.method==='POST'&&(route==='/api/auth/login'||route==='/api/auth/register')){if(limited(req))return send(res,429,{error:'محاولات كثيرة، حاول بعد قليل'});const b=await bodyJson(req,20000),p=phone(b.phone),pw=String(b.password||'');if(!validPhone(p))return send(res,400,{error:'أدخل رقم هاتف مصري صحيح'});if(pw.length<8||pw.length>128)return send(res,400,{error:'كلمة المرور يجب أن تكون بين 8 و128 حرفًا'});let u=await findUser('20'+p);if(route.endsWith('register')){if(u)return send(res,409,{error:'رقم الهاتف مسجل بالفعل'});u=await createUser({id:crypto.randomUUID(),phone:'20'+p,passwordHash:await hash(pw),role:(await countUsers())?'user':'admin'})}else if(!u||!(await verify(pw,u.passwordHash)))return send(res,401,{error:'رقم الهاتف أو كلمة المرور غير صحيحة'});const publicUser={id:u.id,phone:u.phone,role:u.role};res.setHeader('Set-Cookie',`session=${token(publicUser,Date.now()+(b.remember?SESSION_TTL:28800000))}; HttpOnly; SameSite=Lax; Path=/${b.remember?'; Max-Age='+SESSION_TTL/1000:''}`);return send(res,200,{ok:true,user:publicUser})}
if(route==='/api/db'&&req.method==='GET'){if(!auth(req,res))return;return send(res,200,await getState())}
if(route==='/api/db'&&req.method==='PUT'){if(!auth(req,res))return;const data=await bodyJson(req);if(!data||!Array.isArray(data.members)||!Array.isArray(data.classes)||!Array.isArray(data.attendance)||!Array.isArray(data.visits)||!data.settings)return send(res,400,{error:'بيانات غير صالحة'});await updateState(data);return send(res,200,{ok:true})}
if(req.method==='GET'){const f=safe(req.url);if(!f||!fs.existsSync(f)||!fs.statSync(f).isFile())return send(res,404,{error:'Not found'});const ext=path.extname(f).toLowerCase(),types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8'};res.writeHead(200,{'Content-Type':types[ext]||'application/octet-stream','Cache-Control':ext==='.html'?'no-cache':'public, max-age=3600'});return fs.createReadStream(f).pipe(res)}return send(res,405,{error:'Method not allowed'})
}catch(e){console.error(e);return send(res,e.status||500,{error:e.status===413?'حجم البيانات كبير':'حدث خطأ في الخادم'})}}).listen(PORT,'0.0.0.0',()=>console.log(`خدمة الأمير تعمل على http://localhost:${PORT}`))})().catch(e=>{console.error(e);process.exit(1)});
